apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    name: {{ .Values.metadata.name }}
spec:

  volumes:
    - name: secrets
      emptyDir:
        sizeLimit: 5Mi
  initContainers:
    - name: vault-secrets
      image: pavanidevops78/kubernetes:{{ .Values.initContainers.imageVersion }}
      env:
        - name: VAULT_ADDR
          value: "https://vault-internal.pdevops78.online:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/{{ .Values.project_name }}-{{ .Values.component }}
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"

      volumeMounts:
        - name: secrets
          mountPath: /data

    - name: schema
      image: pavanidevops78/kubernetes:{{ .Values.schema.schema_imageVersion }}
      volumeMounts:
        - name: secrets
          mountPath: /data

  containers:
    - name: backend
      image: pavanidevops78/kubernetes:{{ .Values.containers.cont_imageVersion }}

      volumeMounts:
        - name: secrets
          mountPath: /data


---
apiVersion: v1
kind: Service
metadata:
  name: service-01
spec:
  type: ClusterIP
  selector:
    name: {{ .Values.component }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

