apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    appName: frontend
    project_Name: expense
spec:
{{- if .Values.initContainers.enabled }}
  volumes:
    - name: secrets
      emptyDir:
        sizeLimit: 5Mi
  initContainers:
    - name: vault-secrets
      image: pavanidevops78/kubernetes:{{ .Values.initContainers.imageVersion }}
      env:
        - name: VAULT_ADDR
          value: "https://vault-internal.pdevops78.online:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/{{ .Values.labels.project_name }}-{{ .Values.component }}
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"

      volumeMounts:
        - name: secrets
          mountPath: /data

    - name: schema
      image: pavanidevops78/kubernetes:{{ .Values.schema.schema_imageVersion }}
      volumeMounts:
        - name: secrets
          mountPath: /data
{{- end }}

  containers:
    - name: {{ .Values.containers.name }}
      image: pavanidevops78/kubernetes:f1
{{- if .Values.initContainers.enabled }}
      volumeMounts:
        - name: secrets
          mountPath: /data
{{- end }}





