apiVersion: v1
kind: Service
metadata:
  name: frotend
spec:
  selector:
     appName: frontend
     project_Name: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: {{ .Values.service.type }}