apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
spec:
  selector:
     appName: {{ .Values.labels.appName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: {{ .Values.service.type }}