apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-es-default-0
  namespace: elastic-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
