apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  volumes:
    - name: vault-path
      emptyDir: {}
  initContainers:
    - name: vault-secrets
      image: pavanidevops78/kubernetes:v1
      env:
       - name: VAULT_ADDR
         value: https://3.86.88.154:8200
       - name: VAULT_TOKEN
         valueFrom:
           secretKeyRef:
             name: vault-token
             key: token
       - name: SECRET_NAME
         value: common/common
       - name: VAULT_SKIP_VERIFY
         value: "true"

  containers:
    - name: backend
      image:  pavanidevops78/kubernetes:b1
      volumeMounts:
        - name: vault-path
          mountPath: /data

