apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  volumes:
    - name: secrets
      emptyDir:
        sizeLimit: 5Mi
  initContainers:
    - name: vault-secrets
      image: pavanidevops78/kubernetes:v5
      env:
        - name: VAULT_ADDR
          value: "https://3.86.158.194:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/common
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"

      volumeMounts:
        - name: secrets
          mountPath: /data
  containers:
    - name: backend
      image:  pavanidevops78/kubernetes:v3
      volumeMounts:
        - name: secrets
          mountPath: /data

