apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    name: backend
spec:
  volumes:
    - name: secrets
      emptyDir:
        sizeLimit: 5Mi
  initContainers:
    - name: vault-secrets
      image: pavanidevops78/kubernetes:p2
      env:
        - name: VAULT_ADDR
          value: "https://13.222.254.131:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/common
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"

      volumeMounts:
        - name: secrets
          mountPath: /data
  containers:
    - name: backend
      image:  pavanidevops78/kubernetes:p1
      volumeMounts:
        - name: secrets
          mountPath: /data


---
apiVersion: v1
kind: Service
metadata:
  name: service-01
spec:
  type: ClusterIP
  selector:
    name: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

