apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels: nginx
spec:
  volumes:
    - name: secrets
      emptyDir: {}
  containers:
    - name: frontend
      image: pavanidevops78/kubernetes:s2
      volumeMounts:
        - name: secrets
          mountPath: /data

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

