apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    appName: nginx
spec:
  containers:
    - name: frontend
      image: pavanidevops78/kubernetes:s2

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    appName: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

