apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  container:
     - name: nginx
       image: nginx
       volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-path
      emptyDir: {}
