apiVersion: v1
kind: Secret
metadata:
  name: secret-01
data:
  url: Z29vZ2xlLmNvbQ==
  username: YWRtaW4=

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: url
          valueFrom:
            secretKeyRef:
              name: secret-01
              key: url
        - name: username
          valueFrom:
            secretKeyRef:
              name: secret-01
              key: username

