apiVersion: v1
kind: Pod
metadata:
  name: pod-01
  labels:
    app: my-app
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: service-01
spec:
  type: clusterIP
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


# here service spec type "clusterIP is by default



