apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    appName: backend
    projectName: expense
spec:
  volumes:
  - name: secrets
    emptyDir:
      sizeLimit: 5Mi
  initContainers:
    - name: vault-secrets
      image: pavanidevops78/kubernetes:i1
      env:
        - name: VAULT_ADDR
          value: "https://vault-internal.pdevops78.online:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/common
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
  
      volumeMounts:
        - name: secrets
          mountPath: /data
  
    - name: schema
      image: pavanidevops78/kubernetes:b4
      volumeMounts:
        - name: secrets
          mountPath: /data
  containers:
    - name: backend
      image: pavanidevops78/kubernetes:d5
      volumeMounts:
        - name: secrets
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    appName: backend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080



# ClusterIP service type is by default




